name: Take screenshots

on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: cd playwright && npm ci
    - name: Install Playwright
      run: cd playwright && npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        POKERI_USER: ${{ secrets.POKERI_USER }}
        POKERI_PASS: ${{ secrets.POKERI_PASS }}
      run: cd playwright && npx playwright test
    - name: send photo message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: pokeri-ui
        photo: playwright/pokeri-ui.png
        debug: true