name: Take screnshots

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *' # '2 15 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache Playwright browsers
      uses: actions/cache@v2
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install Playwright dependencies
      run: |
        shot-scraper install
    - name: Take shots
      env:
        POKERI_USER: ${{ secrets.POKERI_USER }}
        POKERI_PASS: ${{ secrets.POKERI_PASS }}
      run: |
        shot-scraper multi shots.yml
    - name: Commit and push if anything changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest: ${timestamp}" || exit 0
        git pull --rebase
        git push